# Generated by Django 2.2.27 on 2022-02-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_hrjobpostings_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.CandidateResumes')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumes.HRJobPostings')),
            ],
        ),
    ]
