# Generated by Django 2.2.27 on 2022-02-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateresumes',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
