# Generated by Django 2.2.27 on 2022-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_jobdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrjobpostings',
            old_name='job_date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='hrjobpostings',
            name='description_file',
            field=models.FileField(default='', upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='hrjobpostings',
            name='joining_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='JobDescription',
        ),
    ]
