# Generated by Django 2.2.27 on 2022-03-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_auto_20220320_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrjobpostings',
            name='job_description',
        ),
    ]
